"""
공통 상수 정의
프로젝트 전체에서 사용되는 상수들
"""

# 네트워크 설정
DEFAULT_PORT = 9999
DEFAULT_HOST = '0.0.0.0'
BUFFER_SIZE = 4096
ENCODING = 'utf-8'

# 게임 설정
MIN_PLAYERS = 2
MAX_PLAYERS = 4
TOTAL_ROUNDS = 5
ROUND_TIME = 90  # 초
DEFENSE_INPUT_TIME = 20  # 초
PREPARATION_TIME = 10  # 초

# 더미 패킷 설정
DUMMY_PACKET_INTERVAL_MIN = 1.0  # 초
DUMMY_PACKET_INTERVAL_MAX = 2.0  # 초

# 점수 설정
SCORE_CORRECT_DEFENSE = 10
SCORE_WRONG_DEFENSE = -5
SCORE_MISSED_ATTACK = -10  # HP 감소
SCORE_SUCCESSFUL_ATTACK = 5

# 체력 설정
INITIAL_HP = 100

# 메시지 타입
MSG_TYPE_DUMMY = "DUMMY"
MSG_TYPE_ATTACK = "ATTACK"
MSG_TYPE_DEFENSE = "DEFENSE"
MSG_TYPE_SCORE = "SCORE"
MSG_TYPE_CONNECT = "CONNECT"
MSG_TYPE_DISCONNECT = "DISCONNECT"
MSG_TYPE_GAME_START = "GAME_START"
MSG_TYPE_GAME_END = "GAME_END"
MSG_TYPE_ROUND_START = "ROUND_START"
MSG_TYPE_ROUND_END = "ROUND_END"
MSG_TYPE_PLAYER_LIST = "PLAYER_LIST"
MSG_TYPE_DEFENSE_PHASE = "DEFENSE_PHASE"
MSG_TYPE_ERROR = "ERROR"
MSG_TYPE_INFO = "INFO"

# 게임 상태
STATE_WAITING = "WAITING"
STATE_PREPARATION = "PREPARATION"
STATE_PLAYING = "PLAYING"
STATE_DEFENSE = "DEFENSE"
STATE_ROUND_END = "ROUND_END"
STATE_GAME_END = "GAME_END"
